-- $ sqlite3 ./var/books.db < ./share/books.sql

PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE Users (
Id INTEGER PRIMARY KEY AUTOINCREMENT,
username VARCHAR(255) NOT NULL,
password VARCHAR(255) NOT NULL
);
INSERT INTO Users VALUES(1,'John','pass01');
INSERT INTO Users VALUES(2,'Sam','pass02');
CREATE TABLE Words (
word VARCHAR(50) PRIMARY KEY
);
CREATE TABLE Sessions (
SessionId INTEGER PRIMARY KEY AUTOINCREMENT,
UserId INTEGER NOT NULL,
Word VARCHAR(50) NOT NULL,
MovesCompleted INTEGER DEFAULT 0,
SessionCompleted INTEGER DEFAULT 0,
FOREIGN KEY(UserId) REFERENCES Users(Id),
FOREIGN KEY(Word) REFERENCES Words(word)
);
DELETE FROM sqlite_sequence;
INSERT INTO sqlite_sequence VALUES('Users',2);
COMMIT;